- name: sleep for 120 seconds and continue with play
  wait_for: timeout=120
  delegate_to: localhost

- name: put /root/etcd-operator-config.yaml
  template: src=etcd-operator-config.yaml dest=/root/etcd-operator-config.yaml

- name: check if a Helm release for etcd-operator is present
  shell: helm list --namespace={{ etcd_operator_namespace }} | grep etcd-operator-release
  register: result
  ignore_errors: true

- name: clone the repo
  git: repo=https://github.com/alexclear/charts.git dest=/root/charts

- name: install etcd-operator using a Helm chart
  shell: cd /root/charts/stable && helm install -f /root/etcd-operator-config.yaml etcd-operator --namespace {{ etcd_operator_namespace }} --name etcd-operator-release
  when: result|failed
